# Generated by Django 5.2.18 on 2026-10-07 12:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=40)),
                ('nickname', models.CharField(default='Player', max_length=30)),
                ('years', models.JSONField(default=list)),
                ('choices', models.JSONField(default=list)),
                ('next_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
